Web/Models/TimeTrackerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Web.Models
{
    public class TimeTrackerViewModel : IStartTrackingTime, IStopTrackingTime
    {
        public bool IsTrackingTime { get; set; }
        public string Description { get; set; }
        public Guid? ParentThreadId => LastTrackingThreadId;
        public TimeThreadDto LastTrackingThread { get; set; }
        public Guid LastTrackingThreadId => LastTrackingThread?.Id ?? Guid.Empty;
        public IEnumerable<TimeThreadDto> StoppedThreads { get; set; } = Enumerable.Empty<TimeThreadDto>();
        public IEnumerable<TimeThreadDto> TrackingThreads { get; set; } = Enumerable.Empty<TimeThreadDto>();
    }
}

Web/Controllers/TimeTrackerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Identity;
using Microsoft.AspNet.Identity;
using Web.Models;
using Web.Services;

namespace Web.Controllers
{
    [Authorize]
    public class TimeTrackerController : Controller
    {
        private TimeThreadsHttpClient _timeThreadsHttpClient;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            // TODO: Remove this hack...
            using(var context = new ApplicationDbContext())
            {
                var bearer = context.UserAccessTokens
                    .OrderByDescending(x => x.ExpiresAt)
                    .First(x => x.UserId == this.UserId)
                    .AccessToken;

                _timeThreadsHttpClient = new TimeThreadsHttpClient(bearer);
            }

            base.OnActionExecuting(filterContext);
        }

        public Guid UserId => new Guid(this.User.Identity.GetUserId());

        public async Task<ActionResult> Index()
        {
            var userThreads = (await _timeThreadsHttpClient.GetAll(UserId))
                .OrderByDescending(x => x.StartedAt)
                .ToList();

            var lastTrackingThread = userThreads
                .FirstOrDefault(x => x.StoppedAt == null);

            var model = new TimeTrackerViewModel
            {
                LastTrackingThread = lastTrackingThread,
                IsTrackingTime = lastTrackingThread != null,
                StoppedThreads = userThreads.Where(x => x.StoppedAt != null).OrderByDescending(x => x.StartedAt),
                TrackingThreads = userThreads.Where(x => x.StoppedAt == null).OrderByDescending(x => x.StartedAt)
            };

            return View(nameof(Index), model);
        }

        [HttpPost]
        public async Task<ActionResult> Start(StartTrackingTimePostModel model)
        {
            if (!ModelState.IsValid)
            {
                return await Index();
            }

            await _timeThreadsHttpClient.Start(
                userId: UserId,
                description: model.Description,
                parentThreadId: model.ParentThreadId);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<ActionResult> Stop(StopTrackingTimePostModel model)
        {
            if (!ModelState.IsValid)
            {
                return await Index();
            }

            await _timeThreadsHttpClient.Stop(threadId: model.LastTrackingThreadId);

            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Views/TimeTracker/Index.cshtml
@using Web.Models
@model Web.Models.TimeTrackerViewModel

@{
    ViewData["Title"] = "Track time";
}

<h1>Track time</h1>
<div class="row">
    <section>
        @Html.ValidationSummary()
        @if (!Model.IsTrackingTime)
            {
                using (Html.BeginForm("Start", "TimeTracker", FormMethod.Post))
                {
                <div class="form-group">
                    @Html.LabelFor(x => x.Description)
                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                        <button type="submit" class="btn btn-default">Start</button>
                </div>
            }
        }
        else
        {
            using (Html.BeginForm("Stop", "TimeTracker", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.HiddenFor(x => x.LastTrackingThreadId, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Stop "@Model.LastTrackingThread.Description"</button>
                </div>
            }
            using (Html.BeginForm("Start", "TimeTracker", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.HiddenFor(x => x.ParentThreadId)
                    @Html.LabelFor(x => x.Description)
                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Start another under "@Model.LastTrackingThread.Description"</button>
                </div>
            }
        }
    </section>
</div>
@if (Model.IsTrackingTime)
{
    <div class="row">
        <section>
            <h4>Under tracking:</h4>
            <hr />
            <ul>
                @foreach (var thread in Model.TrackingThreads)
                {
                    string threadText = "";
                    if (thread.StoppedAt == null)
                    {
                        threadText = $"Description: \"{thread.Description}\" / From: {thread.StartedAt:hh:mm:ss}";
                    }
                    else
                    {
                        threadText = GetThreadTextWithDuration(thread);
                    }
                    <li style="margin-left: @(thread.LevelsDeep)cm">threadText</li>
                }
            </ul>
        </section>
    </div>
}
@if (Model.StoppedThreads.Any())
{
    <div class="row">
        <section>
            <h4>Stopped:</h4>
            <hr />
            <ul>
                @foreach (var thread in Model.StoppedThreads)
                {
                    <li style="margin-left: @(thread.LevelsDeep)cm">@GetThreadTextWithDuration(thread)</li>
                }
            </ul>
        </section>
    </div>
}

@functions {

    private static string GetThreadTextWithDuration(TimeThreadDto thread)
    {
        var duration = thread.StoppedAt.Value - thread.StartedAt;
        var threadText = $"Description: \"{thread.Description}\" / Duration: {duration:hh\\:mm\\:ss} / From: {thread.StartedAt:hh:mm:ss} To: {thread.StoppedAt.Value:hh:mm:ss}";
        return threadText;
    }
}